"""
shot_cams - executable camera direction for all 58 shots.

Every entry realises the shot's CAMERA_PLAN line (05_STORYBOARD/CAMERA_PLAN.json):
framing, angle, height, lens, subject scale, composition, motivated motion,
focus, screen direction. Coordinates are world metres in the built scene.

Master axis: sea/ship +X = FRAME RIGHT, tower -X = FRAME LEFT. Default camera
side is -Y of the subject (frame right = +X = sea). `reverse` marks setups
looking back the other way; `exempt` marks the plan's neutral buffers
(macros, POVs, verticals, interiors) that legitimately sit outside the axis.

Entry fields
  subj      subject token (resolved in the built+animated scene) or (x,y,z)
  lens      focal length mm            dist    camera-subject distance m
  h         camera height above subject anchor    az  0=-Y side, 90=+X, 180=+Y
  aim       optional aim offset added to the subject point (composition)
  loc/target  explicit placement (overrides subj/dist/az/h)
  motion    motivated move tuple (see cam_lib) - ('hold',) is the default
  scale     (lo,hi) allowed projected subject-height fraction at the end pose
  subj_h    world height of the framed subject (m)
  fstop     DOF aperture; macros stop down to 2.8
"""

SHOT_CAMS = {
    # ---------------- SC01 - the failed winding, the world revealed ---------------- #
    "SC01_SH001": dict(subj="KEY_WICK", lens=100, dist=0.10, h=0.0, az=-90, fstop=2.8,
                       motion=("hold",), scale=(0.8, 4.5), subj_h=0.05, exempt=True,
                       note="ECU macro on the slipping key, dead-on from her back side. Locked off: nothing moves but the key."),
    "SC01_SH002": dict(subj="GAUGE", lens=100, dist=0.12, h=0.0, az=90, fstop=2.8,
                       motion=("push_in", 0.10), scale=(0.8, 4.5), subj_h=0.09, exempt=True,
                       note="Macro on 92. Very slight push-in - the audience leans toward the failure; 2cm total."),
    "SC01_SH003": dict(subj="GAUGE", lens=100, dist=0.10, h=0.0, az=90, fstop=2.8,
                       motion=("hold",), scale=(0.8, 4.5), subj_h=0.09, exempt=True,
                       note="Static macro. The first true stillness lets the number land."),
    "SC01_SH004": dict(subj="WICK", lens=24, dist=0.5, h=0.35, az=0,
                       motion=("crane_back_up", 18.0, 6.0), scale=(0.005, 0.08), subj_h=0.4,
                       note="The reveal: one continuous crane back and up, macro-ish to extreme wide. Unhurried so the scale change reads as a single thought."),
    "SC01_SH005": dict(subj="WICK_HEAD", lens=50, dist=0.35, h=0.0, az=90, reverse=True,
                       motion=("micro_drift", 0.006, 1), scale=(0.3, 1.0), subj_h=0.09,
                       note="CU at her eye height. One slow 6mm drift across the whole shot - a living ticking machine, not handheld noise."),
    "SC01_SH006": dict(loc=(0.3, -0.6, 0.35), target=(0.0, 0.0, 9.0), lens=35,
                       motion=("hold",), scale=(0.5, 1.6), subj_h=4.0, exempt=True,
                       exclude="WICK",
                       note="POV wide: her gaze up the tower to the dark beacon. Static - it is her gaze, not a camera idea."),
    # ---------------- SC02 - the habit, the ship, the decision ---------------- #
    "SC02_SH001": dict(subj="WICK", lens=35, dist=1.6, h=0.06, az=0,
                       motion=("hold",), scale=(0.2, 0.7), subj_h=0.4,
                       note="Medium low (ankle height) covering her full height; static. The habit is the point."),
    "SC02_SH002": dict(subj="KEY_WICK", lens=100, dist=0.10, h=0.0, az=-90, fstop=2.8,
                       motion=("hold",), scale=(0.8, 4.5), subj_h=0.05, exempt=True,
                       note="Back-height macro insert, identical grammar to SC01_SH001: the repetition of failure is the content."),
    "SC02_SH003": dict(loc=(0.0, 1.0, 0.35), target=(60.0, 30.0, 0.8), lens=200,
                       motion=("hold",), scale=(0.15, 0.7), subj_h=2.5,
                       note="ELS 200mm: the returning ship, frame RIGHT on the master axis. Held - motion would falsify its distance."),
    "SC02_SH004": dict(loc=(0.0, -8.0, 0.25), target=(0.0, 0.0, 8.0), lens=18,
                       motion=("hold",), scale=(0.4, 1.5), subj_h=9.0, exempt=True,
                       note="18mm at the waterline looking up the tower. Static: the height is felt, not pushed."),
    "SC02_SH005": dict(subj="WICK_HEAD", lens=85, dist=0.45, h=0.0, az=60, reverse=True,
                       motion=("hold",), scale=(0.3, 1.2), subj_h=0.09,
                       note="CU 85mm, chest height. Static: the reflection completes the three-point eyeline."),
    "SC02_SH006": dict(subj='WICK', lens=40, dist=1.8, h=0.25, az=0, motion=['hold'], scale=[0.2, 0.7], subj_h=0.4, note='Medium at her eye height; static - she provides the motion and exits frame LEFT (tower direction). QC-13 nudge: camera re-placed for clear subject line of sight (ERR-0004 fix), framing window kept.'),
    # ---------------- SC03 - the crossing begins ---------------- #
    "SC03_SH001": dict(subj='WICK', lens=40, dist=1.5, h=0.25, az=0, motion=['dolly', -0.8, 0.0], scale=[0.2, 0.8], subj_h=0.4, note='Lateral dolly at her height matching her stride: the camera walks with her, motivated by her walk. QC-13 nudge: camera re-placed for clear subject line of sight (ERR-0004 fix), framing window kept.'),
    "SC03_SH002": dict(subj="GAUGE", lens=100, dist=0.11, h=0.0, az=90, fstop=2.8,
                       motion=("hold",), scale=(0.8, 4.5), subj_h=0.09, exempt=True,
                       note="Locked insert grammar: chest macro, dead still."),
    "SC03_SH003": dict(subj="WICK", lens=24, dist=13.0, h=6.1, az=0,
                       motion=("push_in", 11.0), scale=(0.005, 0.1), subj_h=0.4,
                       note="High crane beauty pass with a slow push - the height is earned, the move glacial."),
    "SC03_SH004": dict(subj='WICK', lens=40, dist=1.4, h=0.25, az=0, motion=['dolly', -1.0, 0.0], scale=[0.2, 0.8], subj_h=0.4, note='Tracking medium; foreground poles strobe past - rhythm from the dolly matched to her stride. QC-13 nudge: camera re-placed for clear subject line of sight (ERR-0004 fix), framing window kept.'),
    "SC03_SH005": dict(subj="WICK", lens=35, dist=0.55, h=0.15, az=90,
                       aim=(-3.0, 0.0, -0.1), motion=("hold",), scale=(0.05, 0.6), subj_h=1.0, exempt=True,
                       note="OTS: over her shoulder at the edge, holding on the black water - the next obstacle. Static."),
    # ---------------- SC04 - the flooded streets ---------------- #
    "SC04_SH001": dict(loc=[-2.0, -4.0, 0.68], target=[-2.0, 1.6, 0.3], lens=24, motion=['hold'], scale=[0.02, 0.2], subj_h=0.4, note='Wide at water level: the flood is the reveal. Static. QC-13 nudge: camera re-placed for clear subject line of sight (ERR-0004 fix), framing window kept.'),
    "SC04_SH002": dict(subj="WICK", lens=50, dist=1.8, h=0.0, az=0,
                       motion=("micro_drift", 0.03, 0), scale=(0.25, 0.8), subj_h=0.4,
                       note="Medium at her height. Motivated instability: ONE slow 3cm drift - the effort feels unstable without fake shake."),
    "SC04_SH003": dict(subj='WICK', lens=50, dist=2.2, h=0.0, az=100, reverse=True, motion=['hold'], scale=[0.2, 0.7], subj_h=0.4, note='Static profile from the sea side; she crosses frame. The line gives the traverse legibility. QC-13 nudge: camera re-placed for clear subject line of sight (ERR-0004 fix), framing window kept.'),
    "SC04_SH004": dict(subj="WICK", lens=35, dist=1.2, h=0.35, az=0,
                       motion=("descend", 0.02), scale=(0.1, 0.7), subj_h=0.4,
                       note="The camera goes under with her - the drop must be felt, not observed."),
    "SC04_SH005": dict(loc=(-2.5, 1.2, 0.03), target=(-2.0, 1.6, 0.5), lens=35,
                       motion=("hold",), scale=(0.3, 1.3), subj_h=0.4,
                       note="Static low from the lane floor looking up; she rises past. Her glow is the only warm thing."),
    "SC04_SH006": dict(subj="WICK", lens=50, dist=1.4, h=0.25, az=0,
                       motion=("hold",), scale=(0.3, 0.9), subj_h=0.4,
                       note="Low and tight at coping level; water on the lens (grade/VFX). Imperfect on purpose."),
    # ---------------- SC05 - the gantry, the gust, the loss ---------------- #
    "SC05_SH001": dict(loc=(0.5, -2.5, 0.9), target=(0.0, 4.5, 1.2), lens=28,
                       motion=("hold",), scale=(0.02, 0.2), subj_h=0.4,
                       note="Wide, gantry level low: the destination stays visible during the obstacle. Static."),
    "SC05_SH002": dict(subj="WICK", lens=35, dist=1.6, h=0.0, az=0,
                       motion=("hold",), scale=(0.2, 0.7), subj_h=0.4,
                       note="Medium at her height, static; the gust supplies the motion. Brace against, don't chase."),
    "SC05_SH003": dict(subj="WICK", lens=50, dist=1.8, h=0.0, az=0,
                       motion=("pan_hold", (4.9, 5.8, 0.2)), scale=(0.05, 0.4), subj_h=0.4,
                       note="Follows the pole out of frame with a pan, then holds on the water. The loss gets one clean move, then silence."),
    "SC05_SH004": dict(subj="WICK_HEAD", lens=85, dist=0.4, h=0.0, az=90, reverse=True,
                       motion=("hold",), scale=(0.4, 1.3), subj_h=0.09,
                       note="CU, static, no cut: the stillness IS the beat; the wind drops for her."),
    "SC05_SH005": dict(subj="GAUGE", lens=100, dist=0.10, h=0.0, az=90, fstop=2.8,
                       motion=("hold",), scale=(0.8, 4.5), subj_h=0.09, exempt=True,
                       note="Chest macro, static. Protect the image; let it be looked at."),
    "SC05_SH006": dict(subj="WICK", lens=40, dist=1.5, h=0.0, az=0,
                       motion=("dolly", -0.8, 0.0), scale=(0.2, 0.8), subj_h=0.4,
                       note="Tracking medium; the shielded glow leads the frame. Dolly matched to her guarded walk."),
    "SC05_SH007": dict(subj="GAUGE", lens=100, dist=0.12, h=0.0, az=90, fstop=2.8,
                       motion=("rack", (2.15, 0.0, 1.0)), scale=(0.8, 4.5), subj_h=0.09, exempt=True,
                       note="Macro on the gauge, rack focus gauge->door (story-space anchor at the tower base): hands SC06 its first image in one move."),
    # ---------------- SC06 - the door, the whip, the stair ---------------- #
    "SC06_SH001": dict(loc=(3.5, -2.5, 0.15), target=(1.0, 0.0, 3.0), lens=24,
                       motion=("hold",), scale=(0.3, 1.3), subj_h=3.4, exempt=True,
                       note="Wide low looking up: compress her against the bottom edge under the tower. Static."),
    "SC06_SH002": dict(subj="WICK_HEAD", lens=50, dist=0.5, h=0.35, az=90, reverse=True,
                       motion=("whip", "GAUGE"), scale=(0.3, 1.0), subj_h=0.09,
                       note="Tight on her, then THE single fast move of the film: a 6-frame whip to the gauge at 55%. Motivated by the two-push failure."),
    "SC06_SH003": dict(subj="GAUGE", lens=100, dist=0.10, h=0.0, az=90, fstop=2.8,
                       motion=("hold",), scale=(0.8, 4.5), subj_h=0.09, exempt=True,
                       note="Insert macro, dead still. The quietest moment in the film."),
    "SC06_SH004": dict(loc=(1.9, -0.4, 0.3), target=(0.6, 0.0, 0.3), lens=18,
                       motion=("tilt_to", (0.0, 0.0, 4.5), 0.85), scale=(0.5, 2.0), subj_h=3.5, exempt=True,
                       note="Interior 18mm: she enters; tilt up the stair and keep tilting. The tower is a vertical promise."),
    "SC06_SH005": dict(loc=(2.8, 0.0, 0.35), target=(2.15, 0.0, 1.0), lens=35,
                       motion=("cut_to", (1.0, -0.8, 0.4), (2.9, 0.0, 0.25)),
                       scale=(1.0, 5.0), subj_h=2.0, exempt=True, exclude="WICK",
                       note="POV at the socket, then in-shot hard cut to the reverse at 50%: two angles, no motion. The gap is the information."),
    # ---------------- SC07 - the climb ---------------- #
    "SC07_SH001": dict(loc=(6.0, -14.0, 8.0), target=(2.25, 0.0, 7.0), lens=24,
                       motion=("hold",), scale=(0.3, 1.2), subj_h=9.0, exempt=True,
                       note="EWS: she is a speck on a vertical. Scale is the shot; static."),
    "SC07_SH002": dict(loc=(4.5, -3.0, 7.0), target=(2.6, 0.2, 5.0), lens=50,
                       motion=("tilt_to", (2.6, 0.4, 0.0), 0.6), scale=(0.1, 0.6), subj_h=1.5,
                       note="Follows the torn stair section down out of frame with a tilt, then holds on the void. One motivated move, then nothing."),
    "SC07_SH003": dict(subj="WICK", lens=35, dist=2.5, h=0.0, az=0,
                       motion=("crane_rise", 2.2), scale=(0.1, 0.5), subj_h=0.4,
                       note="Slow rising track matched to her six-reach climb - height felt, not stated."),
    "SC07_SH004": dict(loc=(2.6, 0.3, 9.2), target=(2.3, 0.0, 2.0), lens=135,
                       motion=("hold",), scale=(0.3, 1.5), subj_h=1.0, exempt=True,
                       note="135mm looking down past her hand: the long lens reveals the drop as compressed danger. Static."),
    "SC07_SH005": dict(subj="POLE", lens=85, dist=0.35, h=0.0, az=-45,
                       motion=("hold",), scale=(0.2, 1.2), subj_h=0.05, exempt=True,
                       note="Insert on the wedged pole, then her hand enters frame - two frames, no exposition. Static."),
    "SC07_SH006": dict(subj="WICK", lens=50, dist=1.35, h=0.05, az=30,
                       aim=(0.10, -0.06, 0.0), motion=("hold",), scale=(0.5, 1.6), subj_h=0.4,
                       note="Tight medium with the gauge riding the corner (aim offset). The cost must be visible while she climbs."),
    "SC07_SH007": dict(subj="GAUGE", lens=85, dist=0.22, h=0.0, az=60, fstop=2.8,
                       motion=("hold",), scale=(0.8, 4.5), subj_h=0.09, exempt=True,
                       note="Very tight on the hands, almost abstract. Hold on the broken motion; do not explain."),
    "SC07_SH008": dict(loc=(3.0, -1.5, 8.5), target=(2.25, 0.0, 8.2), lens=35,
                       motion=("hold",), scale=(0.1, 0.6), subj_h=0.4,
                       note="Gallery level medium: she collapses into frame; hold. Let her be still before the cut."),
    # ---------------- SC08 - the chamber, the sacrifice ---------------- #
    "SC08_SH001": dict(loc=[1.9, 0.0, 12.25], target=[0.4, 0.0, 12.8], lens=18, motion=['hold'], scale=[0.3, 1.4], subj_h=2.4, exempt=True, note='Wide from the chamber floor: scale contrast is the whole shot. Static. QC-13 nudge: camera re-placed for clear subject line of sight (ERR-0004 fix), framing window kept.'),
    "SC08_SH002": dict(subj="BURNER", lens=85, dist=0.45, h=0.0, az=-30,
                       motion=("push_in", 0.35), scale=(0.6, 1.6), subj_h=0.10,
                       note="Close on the reaching hands, unhurried 10cm push. It is not an action scene; it is a decision."),
    "SC08_SH003": dict(subj='BURNER', lens=100, dist=0.3, h=0.0, az=-60, fstop=2.8, motion=['hold'], scale=[0.8, 4.5], subj_h=0.15, exempt=True, note='Static tight at burner level: the gap between spark and brass is the point. QC-13 nudge: camera re-placed for clear subject line of sight (ERR-0004 fix), framing window kept.'),
    "SC08_SH004": dict(subj="SPARK", lens=100, dist=0.09, h=0.0, az=-90, fstop=2.8,
                       motion=("hold",), scale=(0.8, 4.5), subj_h=0.06, exempt=True,
                       note="Locked-off macro on the burner heart. No movement, no music. The most important shot in the film."),
    "SC08_SH005": dict(subj="WICK_HEAD", lens=100, dist=0.4, h=0.0, az=90, reverse=True,
                       motion=("hold",), scale=(0.5, 1.5), subj_h=0.09,
                       note="CU on her head; static - the aperture is the only motion. The whole decision without a cut."),
    "SC08_SH006": dict(subj="COIL", lens=100, dist=0.10, h=0.0, az=90, fstop=2.8,
                       motion=("hold",), scale=(0.8, 4.5), subj_h=0.05, exempt=True,
                       note="Macro on the unspooling mainspring, unhurried. The sacrifice is mechanical and must read as mechanical."),
    "SC08_SH007": dict(loc=(1.8, -1.2, 12.1), target=(0.0, 0.0, 13.4), lens=50,
                       motion=("hold",), scale=(0.2, 1.2), subj_h=0.6, exempt=True,
                       note="Held on her silhouette at the burner; the bloom fills the frame without a cut (lighting stage owns the bloom)."),
    # ---------------- SC09 - ignition, the beam, the turn ---------------- #
    "SC09_SH001": dict(loc=(0.0, -2.0, 14.4), target=(30.0, 8.0, 0.0), lens=35,
                       motion=("hold",), scale=(0.02, 0.4), subj_h=2.5,
                       note="Locked wide from the gallery, 8-second protected hold: the beam sweeps black water, sea frame RIGHT. Never covered, no camera motion."),
    "SC09_SH002": dict(loc=[0.0, -1.0, 14.55], target=[60.0, 20.0, 0.5], lens=300, motion=['hold'], scale=[0.25, 0.9], subj_h=2.5, note='300mm from the gallery: the running light pauses, then turns toward harbour. Held - motion would falsify it. QC-13 nudge: camera re-placed for clear subject line of sight (ERR-0004 fix), framing window kept.'),
    "SC09_SH003": dict(subj='WICK', lens=35, dist=2.4, h=0.3, az=-10, motion=['push_in', 1.6], scale=[0.1, 0.45], subj_h=0.4, note="One continuous move: the beacon dies behind the push and the push finds her at the burner's foot. Dawn. QC-13 nudge: camera re-placed for clear subject line of sight (ERR-0004 fix), framing window kept."),
    # ---------------- SC10 - ninety-two turns ---------------- #
    "SC10_SH001": dict(subj='WICK', lens=50, dist=1.5, h=0.15, az=0, motion=['hold'], scale=[0.25, 0.9], subj_h=0.4, note='Low medium, held long enough to be uncomfortable. Do not soften; static. QC-13 nudge: camera re-placed for clear subject line of sight (ERR-0004 fix), framing window kept.'),
    "SC10_SH002": dict(loc=[-0.4, -1.9, 12.3], target=[1.6, -0.5, 12.1], lens=35, motion=['hold'], scale=[0.2, 0.9], subj_h=1.1, exempt=True, note='Wide from inside the chamber, low: the child enters backlit as a silhouette. Static. QC-13 nudge: camera re-placed for clear subject line of sight (ERR-0004 fix), framing window kept.'),
    "SC10_SH003": dict(subj="KEY_CHILD", lens=85, dist=0.4, h=0.0, az=0, fstop=2.8,
                       motion=("hold",), scale=(0.3, 1.3), subj_h=0.08, exempt=True,
                       note="Static close on the hands at kneel height: the hesitation is the beat."),
    "SC10_SH004": dict(subj="KEY_CHILD", lens=100, dist=0.10, h=0.0, az=-90, fstop=2.8,
                       motion=("hold",), scale=(0.8, 4.5), subj_h=0.05, exempt=True,
                       note="Extreme macro, locked-off, geometrically identical to SC01_SH001: the loop. One turn into the back plate."),
    "SC10_SH005": dict(subj="GAUGE", lens=100, dist=0.11, h=0.0, az=90, fstop=2.8,
                       motion=("hold",), scale=(0.8, 4.5), subj_h=0.09, exempt=True,
                       note="Chest macro on the needle at 1; hard cut to black is an edit/grade beat - the camera stays absolutely still."),
}
