"""
Per-shot animation direction for NINETY-TWO TURNS.

Each entry lists acts; t0/t1 are fractions of the shot's frame range (the runner
maps them onto the exact SHOT_LIST frames). Object tokens are resolved by
shot_runner. Timing, gauge values and prop states mirror SHOT_LIST.json so
continuity is preserved by construction.
"""

SPECS = {
# ---------------- SC01 ---------------- #
"SC01_SH001": dict(note="The hook: four dry ratchet turns, then the slip. Weight lives in the CONSTANT stepping.",
    acts=[("key_slip", dict(obj="KEY_WICK", t0=0.05, t1=0.95, turns=4))]),
"SC01_SH002": dict(note="Tooth shears: coil shudder, needle swings up and sags to 92.",
    acts=[("sway", dict(obj="COIL", t0=0.3, t1=0.55, amp=6, period=8, axis=2)),
          ("needle", dict(gauge="GAUGE", t0=0.35, t1=0.9, v0=0, v1=92))]),
"SC01_SH003": dict(note="Stillness with a tremble; the drifting lamp light is the secondary action.",
    acts=[("needle_tremble", dict(gauge="GAUGE", t0=0.1, t1=0.6, v=92)),
          ("flicker", dict(light="LIGHT_1", t0=0.0, t1=1.0, base=50, amp=10, seed=3)),
          ("hold", dict(obj="WICK", t0=0.0, t1=1.0))]),
"SC01_SH004": dict(note="The reveal hold: she is still; one slow head lift gives the reaction.",
    acts=[("hold", dict(obj="WICK", t0=0.0, t1=1.0)),
          ("look", dict(head="WICK_HEAD", t0=0.5, t1=0.95, rot=(0.21, 0, 0)))]),
"SC01_SH005": dict(note="Shutters iris open from black; look down at the chest, then up - the assessing beat.",
    acts=[("iris", dict(eyes="WICK_EYES", t0=0.05, t1=0.35, a=0.05, b=1.0)),
          ("look", dict(head="WICK_HEAD", t0=0.35, t1=0.6, rot=(0.35, 0, 0))),
          ("look", dict(head="WICK_HEAD", t0=0.65, t1=0.95, rot=(-0.28, 0, 0)))]),
"SC01_SH006": dict(note="POV hold - the tower on the horizon. Stillness is the performance; only the distant lamp breathes.",
    acts=[("hold", dict(obj="WICK", t0=0.0, t1=1.0)),
          ("flicker", dict(light="LIGHT_1", t0=0.0, t1=1.0, base=50, amp=4, seed=3))]),
# ---------------- SC02 ---------------- #
"SC02_SH001": dict(note="The daily habit: walk to the pillar, then the practised haul up to the socket.",
    acts=[("walk", dict(actor="WICK", t0=0.0, t1=0.45, dist=(-0.3, 0.1))),
          ("climb", dict(actor="WICK", t0=0.5, t1=0.95, height=1.1, reaches=3))]),
"SC02_SH002": dict(note="The key spins free - three frictionless attempts, aperture tightening in alarm.",
    acts=[("turns_free", dict(obj="KEY_WICK", t0=0.05, t1=0.9, turns=3)),
          ("iris", dict(eyes="WICK_EYES", t0=0.3, t1=0.8, a=1.0, b=0.55))]),
"SC02_SH003": dict(note="The ship: a ponderous bob; the running light is the only urgency.",
    acts=[("bob", dict(obj="SHIP", t0=0.0, t1=1.0, amp=0.06, period=60)),
          ("hold", dict(obj="WICK", t0=0.0, t1=1.0))]),
"SC02_SH004": dict(note="Reverse on the tower - held dread; the buoy rocks on below, indifferent.",
    acts=[("hold", dict(obj="WICK", t0=0.0, t1=1.0)),
          ("sway", dict(obj="BUOY", t0=0.0, t1=1.0, amp=1.5, period=70, axis=1))]),
"SC02_SH005": dict(note="The three-point eyeline: gauge steady, tower in the lenses, one slow look.",
    acts=[("hold", dict(obj="WICK", t0=0.0, t1=1.0)),
          ("look", dict(head="WICK_HEAD", t0=0.3, t1=0.8, rot=(-0.2, 0, 0)))]),
"SC02_SH006": dict(note="Decision: lift the pole, shoulder it, first step frame-left. Pole follows with overlap.",
    acts=[("lift_pole", dict(actor="WICK", pole="POLE", t0=0.1, t1=0.6)),
          ("walk", dict(actor="WICK", t0=0.6, t1=0.98, dist=(-0.35, 0))),
          ("carry_pole", dict(pole="POLE", actor="WICK", t0=0.6, t1=0.98))]),
# ---------------- SC03 ---------------- #
"SC03_SH001": dict(note="Stride-locked countdown: the gauge ticks with every step (92-90-88).",
    acts=[("walk", dict(actor="WICK", t0=0.0, t1=0.95, dist=(-1.2, 0))),
          ("needle", dict(gauge="GAUGE", t0=0.0, t1=0.95, v0=92, v1=88, stepped=True))]),
"SC03_SH002": dict(note="Discrete audible steps 88-86; needle never glides.",
    acts=[("needle", dict(gauge="GAUGE", t0=0.1, t1=0.9, v0=88, v1=86, stepped=True))]),
"SC03_SH003": dict(note="Beauty pass: unhurried walk, tiny stride, head level - wonder, not hurry.",
    acts=[("walk", dict(actor="WICK", t0=0.0, t1=1.0, dist=(-0.7, 0), arc=0.004))]),
"SC03_SH004": dict(note="Past the dead lamps; the one burning lamp flickers behind her (secondary).",
    acts=[("walk", dict(actor="WICK", t0=0.0, t1=0.95, dist=(-1.0, 0))),
          ("flicker", dict(light="LIGHT_1", t0=0.0, t1=1.0, base=50, amp=9, seed=11))]),
"SC03_SH005": dict(note="At the edge: stop with follow-through, head drops to the black water.",
    acts=[("walk", dict(actor="WICK", t0=0.0, t1=0.35, dist=(-0.3, 0))),
          ("look", dict(head="WICK_HEAD", t0=0.45, t1=0.85, rot=(0.3, 0, 0)))]),
# ---------------- SC04 ---------------- #
"SC04_SH001": dict(note="The flood: she stops; the settle IS the reaction.",
    acts=[("hold", dict(obj="WICK", t0=0.0, t1=1.0)),
          ("look", dict(head="WICK_HEAD", t0=0.3, t1=0.8, rot=(0.25, 0, 0)))]),
"SC04_SH002": dict(note="Grip, haul, grip up the stall - weight in the asymmetric easing.",
    acts=[("climb", dict(actor="WICK", t0=0.0, t1=0.9, height=0.55, reaches=3)),
          ("needle", dict(gauge="GAUGE", t0=0.0, t1=0.9, v0=84, v1=80, stepped=True))]),
"SC04_SH003": dict(note="Hand-over-hand on the slick railing; the rail flexes as secondary motion.",
    acts=[("walk", dict(actor="WICK", t0=0.0, t1=0.95, dist=(-1.1, 0), stride=0.09)),
          ("sway", dict(obj="RAIL", t0=0.0, t1=1.0, amp=1.2, period=30, axis=1)),
          ("needle", dict(gauge="GAUGE", t0=0.0, t1=0.95, v0=80, v1=77, stepped=True))]),
"SC04_SH004": dict(note="THE DROP: last grip, then the fall - linear, heavy, no glamour.",
    acts=[("drop_under", dict(actor="WICK", t0=0.0, t1=0.85, depth=0.6)),
          ("needle", dict(gauge="GAUGE", t0=0.1, t1=0.9, v0=77, v1=75))]),
"SC04_SH005": dict(note="Amber eyes in the murk: push off the lane floor, aperture dimmed by water.",
    acts=[("climb", dict(actor="WICK", t0=0.15, t1=0.9, height=0.5, reaches=2)),
          ("iris", dict(eyes="WICK_EYES", t0=0.0, t1=1.0, a=0.5, b=0.8))]),
"SC04_SH006": dict(note="Breaks the surface sparking: haul up, shudder, steam-off settle.",
    acts=[("climb", dict(actor="WICK", t0=0.0, t1=0.5, height=0.35, reaches=2)),
          ("sway", dict(obj="WICK", t0=0.5, t1=0.8, amp=3, period=6, axis=0)),
          ("needle", dict(gauge="GAUGE", t0=0.0, t1=0.9, v0=75, v1=71, stepped=True))]),
# ---------------- SC05 ---------------- #
"SC05_SH001": dict(note="Steps onto the swaying gantry; the walkway flexes under her (secondary).",
    acts=[("walk", dict(actor="WICK", t0=0.0, t1=0.9, dist=(-0.7, 0))),
          ("sway", dict(obj="GANTRY", t0=0.0, t1=1.0, amp=1.5, period=46, axis=1))]),
"SC05_SH002": dict(note="The gust: brace with the pole horizontal - lean overshoots then holds.",
    acts=[("brace", dict(actor="WICK", t0=0.1, t1=0.9)),
          ("pole_horizontal", dict(pole="POLE", t0=0.05, t1=0.4)),
          ("needle", dict(gauge="GAUGE", t0=0.1, t1=0.9, v0=71, v1=68, stepped=True))]),
"SC05_SH003": dict(note="THE POLE GOES: gust takes it, it spins away; her grab closes on nothing.",
    acts=[("spin_away", dict(obj="POLE", t0=0.15, t1=0.95, direction=(1.0, 0.4), turns=3)),
          ("reach_grab", dict(actor="WICK", t0=0.2, t1=0.7)),
          ("iris", dict(eyes="WICK_EYES", t0=0.15, t1=0.5, a=1.0, b=0.6)),
          ("needle", dict(gauge="GAUGE", t0=0.1, t1=0.9, v0=68, v1=66, stepped=True))]),
"SC05_SH004": dict(note="Empty hand, then the tower; the wind drops for the decision.",
    acts=[("look", dict(head="WICK_HEAD", t0=0.1, t1=0.45, rot=(0.3, 0, 0))),
          ("look", dict(head="WICK_HEAD", t0=0.55, t1=0.9, rot=(-0.25, 0, 0.3)))]),
"SC05_SH005": dict(note="The signature: chest opens, the spark lives; she seals the glass against rain.",
    acts=[("reveal_scale", dict(obj="SPARK", t0=0.15, t1=0.6)),
          ("flicker", dict(light="LIGHT_1", t0=0.2, t1=1.0, base=20, amp=6, seed=5)),
          ("iris", dict(eyes="WICK_EYES", t0=0.1, t1=0.5, a=0.6, b=1.0))]),
"SC05_SH006": dict(note="Arm curled across the glass; the spark drains her as she walks.",
    acts=[("walk", dict(actor="WICK", t0=0.0, t1=0.95, dist=(-0.9, 0))),
          ("shield_arm", dict(actor="WICK", t0=0.0, t1=0.25)),
          ("needle", dict(gauge="GAUGE", t0=0.0, t1=0.95, v0=64, v1=60, stepped=True)),
          ("sway", dict(obj="SPARK", t0=0.0, t1=1.0, amp=2, period=20, axis=2))]),
"SC05_SH007": dict(note="60 to 58, then the rack to the door - needle steps stay discrete.",
    acts=[("needle", dict(gauge="GAUGE", t0=0.05, t1=0.6, v0=60, v1=58, stepped=True)),
          ("hold", dict(obj="WICK", t0=0.0, t1=1.0))]),
# ---------------- SC06 ---------------- #
"SC06_SH001": dict(note="Very small against the swollen door; a held breath.",
    acts=[("hold", dict(obj="WICK", t0=0.0, t1=1.0)),
          ("look", dict(head="WICK_HEAD", t0=0.3, t1=0.8, rot=(-0.3, 0, 0)))]),
"SC06_SH002": dict(note="The most expensive action: two shoulder pushes, the gauge pays 58-40.",
    acts=[("push_door", dict(actor="WICK", door="DOOR", t0=0.05, t1=0.85)),
          ("needle", dict(gauge="GAUGE", t0=0.1, t1=0.85, v0=58, v1=40, stepped=True))]),
"SC06_SH003": dict(note="The red arc: needle crosses and holds; the quietest moment in the film.",
    acts=[("needle_tremble", dict(gauge="GAUGE", t0=0.2, t1=0.7, v=40)),
          ("hold", dict(obj="WICK", t0=0.0, t1=1.0))]),
"SC06_SH004": dict(note="Her glow is the only light: enter, and the stair climb begins.",
    acts=[("walk", dict(actor="WICK", t0=0.0, t1=0.35, dist=(-0.5, 0))),
          ("climb", dict(actor="WICK", t0=0.4, t1=0.98, height=1.4, reaches=5)),
          ("flicker", dict(light="LIGHT_1", t0=0.0, t1=1.0, base=10, amp=3, seed=9)),
          ("needle", dict(gauge="GAUGE", t0=0.4, t1=0.98, v0=40, v1=35, stepped=True))]),
"SC06_SH005": dict(note="The stair ends in a gap: look across, then the understanding.",
    acts=[("hold", dict(obj="WICK", t0=0.0, t1=0.4)),
          ("look", dict(head="WICK_HEAD", t0=0.4, t1=0.85, rot=(0.2, 0, 0))),
          ("needle", dict(gauge="GAUGE", t0=0.0, t1=0.9, v0=35, v1=31, stepped=True))]),
# ---------------- SC07 ---------------- #
"SC07_SH001": dict(note="The gale hits flat: brace hard against the iron, spark flaring in rain.",
    acts=[("brace", dict(actor="WICK", t0=0.05, t1=0.9, lean=0.28)),
          ("flicker", dict(light="LIGHT_1", t0=0.0, t1=1.0, base=15, amp=6, seed=7))]),
"SC07_SH002": dict(note="The stair tears away: shudder, then the accelerating fall; no way back.",
    acts=[("tear_fall", dict(obj="STAIR", t0=0.1, t1=0.8, drop=7.0)),
          ("look", dict(head="WICK_HEAD", t0=0.3, t1=0.8, rot=(0.4, 0, 0))),
          ("iris", dict(eyes="WICK_EYES", t0=0.15, t1=0.5, a=1.0, b=0.7))]),
"SC07_SH003": dict(note="The climb: hand over hand, horizon tilting - six reaches with weight.",
    acts=[("climb", dict(actor="WICK", t0=0.0, t1=0.98, height=2.2, reaches=6)),
          ("needle", dict(gauge="GAUGE", t0=0.0, t1=0.98, v0=25, v1=22, stepped=True))]),
"SC07_SH004": dict(note="GRIP LOSS: peeled off, swinging on one arm over the drop.",
    acts=[("swing_one_arm", dict(actor="WICK", t0=0.1, t1=0.9, amp=14, period=28)),
          ("reach_grab", dict(actor="WICK", t0=0.3, t1=0.8)),
          ("needle", dict(gauge="GAUGE", t0=0.1, t1=0.9, v0=22, v1=20))]),
"SC07_SH005": dict(note="Her hand closes on the wedged pole - astonishment opens the shutters.",
    acts=[("reach_grab", dict(actor="WICK", t0=0.1, t1=0.55)),
          ("iris", dict(eyes="WICK_EYES", t0=0.5, t1=0.85, a=0.7, b=1.0)),
          ("hold", dict(obj="POLE", t0=0.0, t1=1.0))]),
"SC07_SH006": dict(note="Pole as brace: haul back onto the iron; the gauge pays 20-14.",
    acts=[("climb", dict(actor="WICK", t0=0.0, t1=0.9, height=0.9, reaches=3)),
          ("carry_pole", dict(pole="POLE", actor="WICK", t0=0.0, t1=0.9)),
          ("needle", dict(gauge="GAUGE", t0=0.0, t1=0.9, v0=20, v1=14, stepped=True))]),
"SC07_SH007": dict(note="The gait breaks down: irregular spacing, spasms - rhythm deliberately destroyed.",
    acts=[("stutter", dict(actor="WICK", t0=0.0, t1=0.98, dist=0.35)),
          ("needle", dict(gauge="GAUGE", t0=0.0, t1=0.98, v0=14, v1=9, stepped=True))]),
"SC07_SH008": dict(note="Over the rail and into the lee: haul, then the collapse.",
    acts=[("climb", dict(actor="WICK", t0=0.0, t1=0.45, height=0.5, reaches=2)),
          ("collapse", dict(actor="WICK", t0=0.5, t1=0.95, tilt=1.2)),
          ("needle", dict(gauge="GAUGE", t0=0.0, t1=0.9, v0=9, v1=6))]),
# ---------------- SC08 ---------------- #
"SC08_SH001": dict(note="Tiny in the enormous brass: a slow walk, head tilted up.",
    acts=[("walk", dict(actor="WICK", t0=0.0, t1=0.6, dist=(-0.4, 0))),
          ("look", dict(head="WICK_HEAD", t0=0.5, t1=0.95, rot=(-0.35, 0, 0)))]),
"SC08_SH002": dict(note="Last rungs; the spark lifts out of her chest - chest goes dark for the first time.",
    acts=[("climb", dict(actor="WICK", t0=0.0, t1=0.4, height=0.4, reaches=2)),
          ("offer", dict(actor="WICK", t0=0.45, t1=0.9, twice=False)),
          ("needle", dict(gauge="GAUGE", t0=0.0, t1=0.9, v0=6, v1=3, stepped=True))]),
"SC08_SH003": dict(note="Offers the spark: nothing catches; repositions; tries again.",
    acts=[("offer", dict(actor="WICK", t0=0.05, t1=0.9, twice=True)),
          ("flicker", dict(light="LIGHT_0", t0=0.0, t1=1.0, base=15, amp=5, seed=4))]),
"SC08_SH004": dict(note="THE REVEAL: locked-off stillness. One aperture micro-tremor is the only motion - do not decorate.",
    acts=[("hold", dict(obj="WICK", t0=0.0, t1=1.0)),
          ("iris", dict(eyes="WICK_EYES", t0=0.4, t1=0.75, a=1.0, b=0.92))]),
"SC08_SH005": dict(note="The whole decision without a cut: socket, chest, decide - aperture tells it.",
    acts=[("look", dict(head="WICK_HEAD", t0=0.05, t1=0.4, rot=(0.25, 0, 0))),
          ("look", dict(head="WICK_HEAD", t0=0.45, t1=0.75, rot=(0.45, 0, 0))),
          ("iris", dict(eyes="WICK_EYES", t0=0.4, t1=0.7, a=1.0, b=0.5)),
          ("iris", dict(eyes="WICK_EYES", t0=0.75, t1=0.98, a=0.5, b=1.0))]),
"SC08_SH006": dict(note="Unspools her own mainspring into the socket: 3-2-1, ratchet engages.",
    acts=[("unspool", dict(actor="WICK", t0=0.05, t1=0.85)),
          ("needle", dict(gauge="GAUGE", t0=0.05, t1=0.9, v0=3, v1=0, stepped=True))]),
"SC08_SH007": dict(note="Eyes go dark; beat of black; IGNITION - the bloom is a light key, not a cheat.",
    acts=[("iris", dict(eyes="WICK_EYES", t0=0.0, t1=0.25, a=1.0, b=0.0)),
          ("bloom", dict(light="LIGHT_1", t0=0.3, t1=0.95, delay=0.35, peak=2000))]),
# ---------------- SC09 ---------------- #
"SC09_SH001": dict(note="The beam sweeps black water - protected 8s hold; the sweep is the beam's, not the camera's.",
    acts=[("beam_sweep", dict(spot="SPOT", t0=0.0, t1=1.0, deg=140)),
          ("bob", dict(obj="BUOY", t0=0.0, t1=1.0, amp=0.08, period=50))]),
"SC09_SH002": dict(note="The running light pauses, then turns toward harbour - ponderous, easy to miss.",
    acts=[("ship_turn", dict(ship="SHIP", t0=0.0, t1=1.0, deg=35)),
          ("bob", dict(obj="SHIP", t0=0.0, t1=1.0, amp=0.06, period=64))]),
"SC09_SH003": dict(note="Dawn; the beacon dims as the dark goes; her silhouette at the burner's foot.",
    acts=[("dim", dict(light="LIGHT_0", t0=0.0, t1=0.7, peak=5000)),
          ("hold", dict(obj="WICK", t0=0.0, t1=1.0)),
          ("bob", dict(obj="BUOY", t0=0.0, t1=1.0, amp=0.07, period=56))]),
# ---------------- SC10 ---------------- #
"SC10_SH001": dict(note="Her shell, held long enough to be uncomfortable. The dim apertures barely breathe; no soften.",
    acts=[("hold", dict(obj="WICK", t0=0.0, t1=1.0)),
          ("iris", dict(eyes="WICK_EYES", t0=0.0, t1=1.0, a=0.35, b=0.28))]),
"SC10_SH002": dict(note="Footsteps: the child enters backlit - a human walk against the machine gait.",
    acts=[("walk", dict(actor="CHILD", t0=0.05, t1=0.85, dist=(-0.7, 0.4), stride=0.35, prefix="CHILD")),
          ("hold", dict(obj="WICK", t0=0.0, t1=1.0))]),
"SC10_SH003": dict(note="Kneels; takes the key; hesitates - the hesitation is the beat.",
    acts=[("kneel_turn", dict(actor="CHILD", key_obj="KEY_CHILD", t0=0.05, t1=0.95))]),
"SC10_SH004": dict(note="One turn - the loop mirrors SC01_SH001 with a single CONSTANT turn that catches.",
    acts=[("turn_key", dict(key_obj="KEY_CHILD", t0=0.2, t1=0.8, turns=1)),
          ("settle", dict(key_obj="KEY_CHILD", t0=0.8, t1=1.0))]),
"SC10_SH005": dict(note="The coil catches; shutters flicker; the needle lifts off zero; cut on the click.",
    acts=[("coil_catch", dict(actor="WICK", t0=0.1, t1=0.6)),
          ("iris", dict(eyes="WICK_EYES", t0=0.4, t1=0.75, a=0.0, b=0.35)),
          ("needle", dict(gauge="GAUGE", t0=0.5, t1=0.95, v0=0, v1=1))]),
}

PRINCIPLES = {
    "walk": ["anticipation", "arcs", "overlapping action", "follow-through", "spacing"],
    "climb": ["arcs", "overlapping action", "weight", "spacing"],
    "brace": ["anticipation", "weight", "follow-through"],
    "collapse": ["weight", "follow-through", "timing"],
    "look": ["reaction", "timing"],
    "iris": ["facial performance", "reaction", "timing"],
    "needle": ["timing", "spacing"],
    "needle_tremble": ["secondary action", "timing"],
    "key_slip": ["timing", "follow-through"],
    "turns_free": ["timing", "reaction"],
    "spin_away": ["follow-through", "arcs", "timing"],
    "reach_grab": ["anticipation", "arcs", "follow-through"],
    "push_door": ["weight", "anticipation", "follow-through"],
    "turn_key": ["timing"],
    "unspool": ["weight", "timing", "secondary action"],
    "kneel_turn": ["weight", "timing", "follow-through"],
    "flicker": ["secondary action"],
    "bob": ["secondary action", "overlapping action"],
    "sway": ["secondary action", "follow-through"],
    "tear_fall": ["anticipation", "weight", "spacing"],
    "bloom": ["timing"],
    "dim": ["timing"],
    "beam_sweep": ["timing"],
    "stutter": ["spacing", "weight"],
    "drop_under": ["weight", "timing", "secondary action"],
    "offer": ["anticipation", "overlapping action", "reaction"],
    "reveal_scale": ["timing", "arcs"],
    "ship_turn": ["weight", "timing"],
    "hold": ["timing"],
    "lift_pole": ["weight", "anticipation"],
    "carry_pole": ["overlapping action"],
    "pole_horizontal": ["reaction"],
    "shield_arm": ["secondary action"],
    "swing_one_arm": ["weight", "follow-through"],
    "coil_catch": ["timing", "secondary action"],
    "settle": ["follow-through"],
    "head_drop": ["weight"],
}
